### PR TITLE
fix exit code check #41

### PR DESCRIPTION
**Pull request by LasaleFamine**
A correct handler for the **exit code** from Nightwatch.
Now the **exit code** on `process.exit()` will be defined by the Nightwatch process itself.

I tested it and I'm able to handle the error on testing my application now.
Tell me what you think about. I hope it helps.

### CODE REVIEW

**Comment by tatsuyafw** [comment]
Hi, @LasaleFamine 

Sorry for the late response.

I have a question about your comment (#41)

>The success variable will never be false. Instead it is always an object with arrays relatives to your >personal suite test.

I'v tested and confirmed the success variable was false.
My sample codes:

- gulpfile.js

```js
var gulp = require('gulp');
var nightwatch = require('gulp-nightwatch');

gulp.task('default', function() {
  gulp.src('')
    .pipe(nightwatch({
      configFile: 'nightwatch.json'
    }));
});
```

- nightwatch.json

```json
{
  "src_folders" : [ "tests" ],
  "output_folder"  : "reports",
  "custom_commands_path" : "",
  "custom_assertions_path" : "",
  "globals_path" : "",

  "selenium" : {
    "start_process" : false,
    "server_path" : "",
    "log_path" : "",
    "host" : "127.0.0.1",
    "port" : 4444,
    "cli_args" : {
      "webdriver.chrome.driver" : "",
      "webdriver.ie.driver" : ""
    }
  },

  "test_settings" : {
    "default" : {
      "launch_url" : "http://localhost",
      "selenium_port"  : 4444,
      "selenium_host"  : "localhost",
      "silent": true,
      "screenshots" : {
        "enabled" : false,
        "path" : ""
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "javascriptEnabled": true,
        "acceptSslCerts": true
      }
    }
  }
}
```

- background.js

```js
var path = require('path');
var nightwatch = require('nightwatch');
var originalArgv = JSON.parse(process.argv[2]);

nightwatch.cli(function(argv) {
  for (var key in originalArgv) {
    if (key === 'env' && originalArgv[key].indexOf(',') > -1 && argv['parallel-mode'] === true) {
      continue;
    }
    argv[key] = originalArgv[key];
  }

  if (argv.test) {
    argv.test = path.resolve(argv.test);
  }

  nightwatch.runner(argv, function(success) {
    if (!success) {
      // modified
      console.log("success:", success)
      console.log("Failed...")
      process.exit(1);
    } else {
      process.exit(0);
    }
  });
});
```

- tests/npm.js

```js
module.exports = {
  'Demo test Npmjs' : function (browser) {
    browser
      .url('https://www.npmjs.com')
      .assert.title('npm-failed') // fail here
      .end();
  }
};
```

- Console outputs:

```
[tatsuya@oort gulp-nightwatch-sandbox]$ gulp
[21:13:57] Using gulpfile ~/tmp/gulp-nightwatch-sandbox/gulpfile.js
[21:13:57] Starting 'default'...
[21:13:57] Finished 'default' after 6.3 ms
[21:13:57] log file
[21:13:57] Starting nightwatch...

[Npm] Test Suite
====================

Running:  Demo test Npmjs
 ✖ Testing if the page title equals "npm-failed".  - expected "npm-failed" but got: "npm"
    at Object.module.exports.Demo test Npmjs (/Users/tatsuya/tmp/gulp-nightwatch-sandbox/tests/npm.js:5:15)


FAILED:  1 assertions failed (6.166s)

 _________________________________________________

 TEST FAILURE:  1 assertions failed, 0 passed. (6.213s)

 ✖ npm

   - Demo test Npmjs (6.166s)
   Testing if the page title equals "npm-failed".  - expected "npm-failed" but got: "npm"
       at Object.module.exports.Demo test Npmjs (/Users/tatsuya/tmp/gulp-nightwatch-sandbox/tests/npm.js:5:15)

success: false
Failed...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: nightwatch exited with code 1
[tatsuya@oort gulp-nightwatch-sandbox]
```

**Comment by tatsuyafw** [comment]
Please let me know about your test codes.

**Comment by LasaleFamine** [comment]
Hi @tatsuyafw,
thanks for your reply.

It was my mistake not specify that I'm running in **parallel** my test suites.

Please, add the following object to your to your configuration file and you will able to reproduce my issue:
```
{
  ...

  "selenium" : {
   ...
    }
  },

   // Perform tests in parallel where possible
  "test_workers": {
    "enabled": true,
    "workers": "auto"
  },
  "test_settings" : {
   ...
    }
  }
}
```
Thinking about this, my PR is not ready to be merge, because we need to handle also this situation of *parallel* case.
I will get back this evening, and if you think is ok, I will fix this PR.

Btw, I'm going to fix my issue's message adding this particularity

**Comment by LasaleFamine** [comment]
Here I'm again.

I think I found the solution.
Really, the second param of the `nightwatch.runner()` function is available only when the tests are running in **parallel**.

The solution code:
``` js
nightwatch.runner(argv, function(success, code) {
    console.log("code =>", code)
    console.log("success => ", success)
    let exitCode = code === 1 ? code : success ? 0 : 1;
    console.log("new exitCode => ", exitCode)
    process.exit(exitCode)
  });
```

### Result test **NO parallel**  
#### ***fail***:
```
   ERROR: Unable to locate element: "#view-password input[name=textinput]" using: css selector
       at Object.module.exports.Test login NOT working (/night-test/test/e2e/main.js:14:8)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)



code => undefined
success =>  false
new exitCode =>  1
[00:28:44] Finished 'func' after 4.78 s
```

#### ***success***:
```
Running:  Test login working
 ✔ Element <body> was visible after 221 milliseconds.

OK. 1 assertions passed. (2.444s)

code => undefined
success =>  true
new exitCode =>  0
[00:30:13] Finished 'func' after 3.06 s
```

### Result test **parallel**

#### ***fail***
```
   - Test login NOT working (3.968s)
   Timed out while waiting for element <input[type=submit]> to be present for 1000 milliseconds.  - expected "visible" but got: "not found"
       at Object.module.exports.Test login NOT working (/night-test/test/e2e/main.js:15:8)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)

code => 1
success =>  { main: [] }
new exitCode =>  1
[00:48:19] Finished 'func' after 4.83 s
```

#### ***success***
```
 main   Results for:  Test login working
 main   ✔ Element <body> was visible after 204 milliseconds.
 main   OK. 1 assertions passed. (2.309s)

  >> main finished.


code => 0
success =>  { main: [] }
new exitCode =>  0
```

I hope it's good! @tatsuyafw

**Comment by cr3** [comment]
I was about to submit a similar pull request and I found that just calling `nightwatch.runner(argv);`, without a function, had the desired outcome. The problem is that the function is called from this code in nightwatch.js:

```
          if (done) {
            try {
              done(self.childProcessOutput, code);
            } catch (err) {
              done(err);
            }
          }

          if (code) {
            process.exit(code);
          }
```

Therefore, the function might be called with two arguments, `childProcessOutput, code`, or one argument, `error`. Rather than try to workaround this inconsistent behavior, just not passing a functions exits with the expected code.

**Comment by LasaleFamine** [comment]
@cr3 that's cool! Thanks for your reply. 
I just tested your case and it works like a charm. I made the same tests of my comment up here and results are the same too.

So, @tatsuyafw, I'm going to commit this change suggested by @cr3.

Thanks again.

**Comment by tatsuyafw** [comment]
@LasaleFamine @cr3 

Awesome!!!
thank you for your contribution 😄

**Comment by tatsuyafw** [comment]
I've released as `v0.3.2`.

**Pull request merged**
